// Copyright (c) 2009, 2012, Willow Garage, Inc.
// Copyright (c) 2026, moveit-rs contributors
// SPDX-License-Identifier: BSD-3-Clause
//
// Ported from moveit2 @ e017c91ee12984393a28ba246075c65f69cde3bf:
//   moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_parameters.hpp
//   moveit_planners/chomp/chomp_motion_planner/src/chomp_parameters.cpp
//   moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_utils.hpp
//   moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_trajectory.hpp
//   moveit_planners/chomp/chomp_motion_planner/src/chomp_trajectory.cpp
//   moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_cost.hpp
//   moveit_planners/chomp/chomp_motion_planner/src/chomp_cost.cpp
//   moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/chomp_optimizer.hpp
//   moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp
//   moveit_planners/chomp/chomp_motion_planner/include/chomp_motion_planner/multivariate_gaussian.hpp

//! CHOMP (Covariant Hamiltonian Optimization for Motion Planning), ported
//! from upstream's `moveit_planners/chomp` package.
//!
//! # `chomp_interface/` is not ported
//!
//! Upstream `moveit_planners/chomp` splits into two subpackages:
//! `chomp_motion_planner/` (the algorithm and its data structures — no ROS
//! type anywhere) and `chomp_interface/` (a `pluginlib` `PlanningContext`
//! adapter exposing it to `move_group`). Only `chomp_motion_planner/` is
//! ported here. `chomp_interface/` is excluded per `PORTING-PLAN.md` D1/D2:
//! this port's core crates reference no ROS type at all, and
//! `chomp_interface`'s reason to exist — being a `pluginlib`-loadable
//! `planning_interface::PlanningContext` — is exactly the `move_group`
//! drop-in shape D1 puts out of scope for the core. Nothing in
//! `chomp_interface/` is algorithmic; it only adapts `ChompPlanner` (see
//! below) to ROS parameters and a live `PlanningScene`.
//!
//! # Scope so far: 7 of 7 upstream files
//!
//! `chomp_motion_planner/` has 7 header/source (or header-only) units:
//! `chomp_cost`, `chomp_optimizer`, `chomp_parameters`, `chomp_planner`,
//! `chomp_trajectory` (`.hpp`+`.cpp` pairs), plus the header-only
//! `chomp_utils.hpp` and `multivariate_gaussian.hpp` — confirmed against
//! `chomp_motion_planner/CMakeLists.txt`'s `add_library` source list (5
//! `.cpp` files) plus the two header-only units, and against every `.h`
//! file in the package being an autogenerated `.hpp`-forwarding
//! deprecation shim with no content of its own
//! (`create_deprecated_headers.py`, moveit#3113).
//! Round 15 ported and audited 3: `chomp_parameters`, `chomp_utils`,
//! `chomp_trajectory`. Round 16 added a 4th: `chomp_cost`. Round 17 added a
//! 5th, `chomp_optimizer`, but only its model/collision-independent numeric
//! core. Round 19 ported the remaining `chomp_optimizer` symbols — the
//! `ChompOptimizer` struct itself, `optimize()`, and its collision-coupled
//! methods — once it was established that its only collision-backend
//! dependency, `getCollisionGradients`, was already ported; see
//! [`optimizer`]'s own module doc for the full account of what changed and
//! why round 17's "collision-coupled, not portable" classification did not
//! hold up. `multivariate_gaussian.hpp` (round 18's 6th file) is not this
//! crate's own copy: it depends on `cspace_core::sampling::MultivariateGaussian`
//! — see below. Round 17 deliberately deferred the 8th, `chomp_planner`,
//! reasoning it should wait until the optimizer it drives was solid; round
//! 19 re-deferred it as "ROS-message-shaped, out of scope" without
//! measuring it. Round 20 measured it (`rg -n 'req\.' chomp_planner.cpp`
//! against its two upstream parameter types, `PORTING-PLAN.md` §154's
//! review) and ported it as [`planner::solve`] — see that module's own doc
//! for the field-by-field count.
//!
//! # `multivariate_gaussian.hpp`: depends on `cspace_core::sampling`, not a local copy
//!
//! Round 18 gave this crate its own transcription of
//! `chomp::MultivariateGaussian`, reasoning that upstream's algorithmically
//! identical STOMP sibling class lived in `ros-industrial/stomp`
//! (Apache-2.0) while CHOMP's upstream is BSD-3-Clause — and that porting
//! both under one `SPDX-License-Identifier` in a shared `cspace_core::sampling`
//! crate would mislabel one side. **That premise was wrong.** The actual
//! upstream path for STOMP's copy that `cspace_core::sampling` ports from is
//! `moveit_planners/stomp/include/stomp_moveit/math/multivariate_gaussian.hpp`
//! — a file inside the `moveit2` tree itself (confirmed by reading its
//! header: `Software License Agreement (BSD License)`, `Copyright (c) 2009,
//! Willow Garage, Inc.`), not a file from the separate `ros-industrial/stomp`
//! Apache-2.0 repository. Both upstream headers `cspace_core::sampling` ports from
//! are therefore BSD-3-Clause end to end, and a shared struct under
//! `SPDX-License-Identifier: BSD-3-Clause` mislabels nothing. Round 19
//! deleted this crate's local copy and switched to `cspace_core::sampling`'s
//! [`MultivariateGaussian`] (re-exported here), after proving byte-for-byte
//! that `MultivariateGaussian::sample_with_covariance` consumes the RNG in
//! the same order/count and produces the same output as the deleted local
//! `sample` — same standard-normal draw loop, same
//! `mean + covariance_cholesky * draws` combination, for the same seeded
//! `ChaCha8Rng`.
//!
//! It has no live consumer yet in this crate beyond `ChompOptimizer`'s
//! `initialize()`, which constructs one per joint
//! (`MultivariateGaussian(Eigen::VectorXd::Zero(...),
//! joint_costs_[i].getQuadraticCostInverse())`) but never samples it: that
//! construction exclusively feeds the Hamiltonian-Monte-Carlo perturbation
//! path (`perturbTrajectory`/`getRandomMomentum`/`updateMomentum`/
//! `updatePositionFromMomentum`), and every call site of that path in
//! `optimize()` is commented out upstream — see [`optimizer`]'s module doc
//! for the full account, including that three of those four methods have no
//! implementation anywhere in `chomp_optimizer.cpp` at all.
//!
//! # Symbol audit: `chomp_parameters.{hpp,cpp}`
//!
//! - `ChompParameters` (class) — ported as [`parameters::ChompParameters`].
//!   All 20 public data members ported as public fields with upstream's
//!   exact default-constructor values; `setRecoveryParams` ported as
//!   [`parameters::ChompParameters::set_recovery_params`];
//!   `setTrajectoryInitializationMethod` ported as
//!   [`parameters::ChompParameters::set_trajectory_initialization_method`],
//!   kept a validated `String` rather than redesigned into an enum — see
//!   that method's doc comment for why. `VALID_INITIALIZATION_METHODS`
//!   ported as [`parameters::VALID_INITIALIZATION_METHODS`]. The default
//!   destructor (`virtual ~ChompParameters()`) has no Rust equivalent to
//!   port; `virtual` exists upstream only so a subclass (none exists in
//!   this package) could override it.
//!
//! # Symbol audit: `chomp_utils.hpp`
//!
//! - `DIFF_RULE_LENGTH` — ported as [`utils::DIFF_RULE_LENGTH`].
//! - `DIFF_RULES` — ported as [`utils::DIFF_RULES`].
//! - `normalizeAnglePositive` — ported as [`utils::normalize_angle_positive`].
//! - `normalizeAngle` — ported as [`utils::normalize_angle`].
//! - `shortestAngularDistance` — ported as [`utils::shortest_angular_distance`].
//! - `robotStateToArray` — ported as [`utils::robot_state_to_array`].
//!
//! # Symbol audit: `chomp_trajectory.{hpp,cpp}`
//!
//! - `ChompTrajectory` (class) — ported as [`trajectory::ChompTrajectory`].
//!   The duration-based and num-points-based constructors are ported as
//!   [`trajectory::ChompTrajectory::from_duration`] and
//!   [`trajectory::ChompTrajectory::from_num_points`]; the copy-with-padding
//!   constructor as [`trajectory::ChompTrajectory::from_source_trajectory`].
//!   The `trajectory_msgs::msg::JointTrajectory`-typed constructor is
//!   excluded (D1): its signature carries a ROS message type directly, and
//!   this crate has no dependency on any ROS message crate at all (see this
//!   crate's `Cargo.toml`), so nothing anywhere in it constructs a
//!   `ChompTrajectory` from one. `operator()` (both overloads) is ported as
//!   `impl `[`std::ops::Index`]`/`[`std::ops::IndexMut`]` for
//!   `[`trajectory::ChompTrajectory`]` on `(usize, usize)``. All other
//!   accessors and the three `fillIn*` methods, `fillInFromTrajectory`,
//!   `assignCHOMPTrajectoryPointFromRobotState` and `getJointVelocities` are
//!   ported as their `snake_case` equivalents on
//!   [`trajectory::ChompTrajectory`] — see that module's own doc comment for
//!   the full name mapping and every deviation from upstream.
//!   `getFreeTrajectoryBlock`/`getFreeJointTrajectoryBlock` are ported
//!   (round 17, once `chomp_optimizer`'s real call sites were known) as
//!   [`trajectory::ChompTrajectory::free_trajectory_block_mut`]/
//!   [`trajectory::ChompTrajectory::free_joint_trajectory_block_mut`] — see
//!   that module doc's own deviation note. The private `init` has no
//!   separate Rust equivalent: every public constructor allocates its
//!   matrix directly via `DMatrix::zeros` instead.
//!
//! # Symbol audit: `chomp_cost.{hpp,cpp}`
//!
//! - `ChompCost` (class) — ported as [`cost::ChompCost`]. The constructor is
//!   ported as [`cost::ChompCost::new`], with the unused `joint_number`
//!   parameter dropped — see that method's and the module's own doc
//!   comments for why. `getQuadraticCostInverse`/`getQuadraticCost` are
//!   ported as [`cost::ChompCost::quadratic_cost_inverse`]/
//!   [`cost::ChompCost::quadratic_cost`] with no behavioral change.
//!   `scale` is ported as [`cost::ChompCost::scale`], now fallible: a
//!   division/NaN-guard audit found upstream's `1.0 / scale` in
//!   `chomp_cost.cpp:97-103` unguarded, so a `0.0`/non-finite `scale`
//!   silently poisons `quad_cost_inv_` with `Infinity`/`NaN` instead of
//!   failing — see that method's own doc comment for the guard and why
//!   this crate's own `ChompOptimizer::new` call site can never trigger it.
//!   `getCost`/`getDerivative`/`getMaxQuadCostInvValue`
//!   are ported as [`cost::ChompCost::cost`]/[`cost::ChompCost::derivative`]/
//!   [`cost::ChompCost::max_quad_cost_inv_value`], each now fallible where
//!   upstream would assert, silently return `NaN`, or read out of bounds —
//!   see [`cost`]'s own module doc for the full account, including the
//!   `quad_cost_inv_` decomposition-family check the round-16 dispatch
//!   asked for. The private `getDiffMatrix` is ported as
//!   [`cost::ChompCost`]'s private `diff_matrix`, transcribed tap-for-tap
//!   including its boundary-truncation behavior (not reflected or
//!   renormalized at the ends) — pinned by a dedicated boundary-vs-interior
//!   unit test per the round-16 dispatch's warning that a wrong boundary
//!   rule leaves interior rows looking correct. The default destructor
//!   (`virtual ~ChompCost()`) has no Rust equivalent, same reasoning as
//!   `ChompParameters`'s.
//!
//! # Symbol audit: `chomp_optimizer.{hpp,cpp}`
//!
//! Read in full (both the 219-line header and the 992-line source) against
//! the pinned SHA. Every symbol is classified below; see [`optimizer`]'s
//! own module doc for the full reasoning behind each classification,
//! including why round 17's "collision-coupled, not portable" verdict on
//! `ChompOptimizer` itself did not hold up.
//!
//! - Ported as free functions in [`optimizer`] (kept as free functions, not
//!   folded into `ChompOptimizer` methods, even though `ChompOptimizer` is
//!   now ported too — see [`optimizer`]'s module doc for why): the inline
//!   `getPotential` → [`optimizer::get_potential`];
//!   `calculateSmoothnessIncrements` →
//!   [`optimizer::calculate_smoothness_increments`];
//!   `calculateTotalIncrements` → [`optimizer::calculate_total_increments`]
//!   (round 17's weighted-combination callout — see [`optimizer`]'s doc
//!   for the exact [`parameters::ChompParameters`] field-name mapping);
//!   `addIncrementsToTrajectory` → [`optimizer::add_increments_to_trajectory`];
//!   `getSmoothnessCost` → [`optimizer::get_smoothness_cost`];
//!   `handleJointLimits` → [`optimizer::handle_joint_limits`].
//! - Ported as `ChompOptimizer` itself, this round (round 19): the struct,
//!   constructor, `isInitialized()`, `isCollisionFree()` →
//!   [`optimizer::ChompOptimizer`],
//!   [`optimizer::ChompOptimizer::new`],
//!   [`optimizer::ChompOptimizer::is_initialized`],
//!   [`optimizer::ChompOptimizer::is_collision_free`]; `optimize()` →
//!   [`optimizer::ChompOptimizer::optimize`] (its termination condition —
//!   round 17's other callout — is now real, executed code, transcribed in
//!   full in [`optimizer`]'s module doc rather than left a specification);
//!   `performForwardKinematics` →
//!   [`optimizer::ChompOptimizer::perform_forward_kinematics`];
//!   `getCollisionCost`, `getTrajectoryCost` → private `get_collision_cost`,
//!   [`optimizer::ChompOptimizer::get_trajectory_cost`];
//!   `calculateCollisionIncrements`, `calculatePseudoInverse`, `getJacobian`
//!   → private `calculate_collision_increments`, `calculate_pseudo_inverse`,
//!   `get_jacobian`; `computeJointProperties`, `setRobotStateFromPoint` →
//!   private `compute_joint_properties`, `set_robot_state_from_point`;
//!   `registerParents`/the private `isParent` → collapsed into one
//!   stateless private helper, `ChompOptimizer::is_ancestor_or_self`;
//!   `isCurrentTrajectoryMeshToMeshCollisionFree` → an injected
//!   `mesh_to_mesh_collision_free` closure parameter on `optimize()`, not a
//!   method (a design decision needing sign-off — see [`optimizer`]'s
//!   module doc). `destroy()` is not ported: its upstream body is a no-op
//!   RAII hook, structurally unnecessary once `Drop` exists (PORTING-PLAN.md
//!   D1). This became possible once it was established, round 19 (the same
//!   round `ChompOptimizer` itself was ported, per this section's own
//!   heading above), that `hy_env_`/`CollisionEnvHybrid` — round 18's cited
//!   blocker — has exactly
//!   5 references in `chomp_motion_planner/`, and the only method ever
//!   called on it, `getCollisionGradients`, is `CollisionEnvHybrid`'s own
//!   one-line forward to `CollisionEnvDistanceField::getCollisionGradients`,
//!   already ported as
//!   [`cspace_collision::distance_field::DistanceFieldCollisionCache::get_collision_gradients`].
//!   `hy_env_`/`planning_scene_`/`full_trajectory_`/`gsr_` are not stored as
//!   struct fields at all in this port — see
//!   [`optimizer::ChompCollisionContext`] and [`optimizer`]'s module doc for
//!   the external-resource-as-parameter design and why `gsr_` is always
//!   function-local. That last choice had one real consequence, surfaced
//!   and documented rather than silently absorbed: `cspace_collision::distance_field`
//!   had no way to reproduce upstream's `gsr_`-reuse pattern, which left
//!   `GradientInfo::sphere_locations` empty through this crate's only
//!   access path (rounds 19-25) — a genuine API gap in
//!   `cspace_collision::distance_field` (another worker's crate), reported and worked
//!   around here rather than fixed. `cspace_collision::distance_field` round 25
//!   (`f5328da`) closed the gap directly (not by porting the `gsr_`-reuse
//!   mechanism itself, which stays unported — see
//!   `cspace_collision::distance_field::DistanceFieldCollisionCache::new`'s own doc
//!   comment for that remaining, purely-performance gap); this crate's
//!   workaround was removed the same round (`5293abd`). See [`optimizer`]'s
//!   module doc, "Closed API gap: `GradientInfo::sphere_locations` (rounds
//!   19-26)", for the full account with upstream/downstream line citations.
//! - Not ported, confirmed dead in upstream itself (not merely out of
//!   scope): `debugCost` (unused `std::cout` helper, no call site anywhere
//!   in `chomp_optimizer.cpp`); `perturbTrajectory`, `getRandomMomentum`,
//!   `updateMomentum`, `updatePositionFromMomentum` (the HMC path — every
//!   call site in `optimize()` is commented out, and the latter three have
//!   no implementation anywhere in the 992-line source at all, only header
//!   declarations).
//!
//! # Symbol audit: `multivariate_gaussian.hpp`
//!
//! - `MultivariateGaussian` (class) — ported as
//!   `cspace_core::sampling::`[`MultivariateGaussian`] (re-exported here), not a
//!   symbol local to this crate — see the "depends on `cspace_core::sampling`"
//!   section above for why. `sample` is ported as
//!   [`MultivariateGaussian::sample_with_covariance`]: CHOMP's `sample` has
//!   no `use_covariance` branch to reconcile (that is STOMP's sibling class),
//!   so it maps onto the one of `cspace_core::sampling`'s two named methods that
//!   always applies the covariance. See `cspace_core::sampling`'s own module doc
//!   for its full symbol mapping and deviations (fallible construction,
//!   `size_` derived rather than stored, etc.) — not re-documented here,
//!   since that crate owns the port.
//!
//! # Symbol audit: `chomp_planner.{hpp,cpp}`
//!
//! Read in full (57-line header, 309-line source) against the pinned SHA.
//!
//! - `ChompPlanner` (class) — has no Rust struct: upstream's class exists
//!   only to hold one method, `solve`, with no fields and no constructor of
//!   its own (the default one). Ported as the free function [`planner::solve`]
//!   instead.
//! - `ChompPlanner::solve` — ported as [`planner::solve`]. See that
//!   function's own module doc for the field-coverage measurement behind
//!   porting it (`eb4fa4e`), and its own doc comment for the exact
//!   `chomp_planner.cpp` line ported at each step, every `MoveItErrorCode`
//!   mapping, and the two named deviations
//!   ([`planner::GoalJointConstraint`]'s "not `cspace_planning::constraints::JointConstraint`",
//!   [`planner::ChompGoal`]'s "joint-only by construction").
//! - The anonymous-namespace `getLogger()` helper and every `RCLCPP_*` call
//!   site — not ported: no logging framework exists anywhere in this
//!   workspace (D1), matching every other crate's convention.
//! - `#include <tf2/...>`, `tf2_eigen`, `tf2_geometry_msgs` — read and
//!   confirmed vestigial: `grep -n 'tf2::\|tf2_geometry\|tf2::doTransform'
//!   chomp_planner.cpp` (pinned SHA) has zero hits inside `solve`'s body;
//!   the includes bring in no symbol `solve` actually uses.
//!
//! # Completion condition
//!
//! Stated as a check on the files audited so far, not a claim about the
//! crate: `chomp_parameters.{hpp,cpp}`, `chomp_utils.hpp`,
//! `chomp_trajectory.{hpp,cpp}`, `chomp_cost.{hpp,cpp}`,
//! `chomp_optimizer.{hpp,cpp}`, `multivariate_gaussian.hpp`, and
//! `chomp_planner.{hpp,cpp}` are each read in full against the pinned SHA
//! and every symbol in them is classified above as ported (with its Rust
//! name), D-decision-excluded (with the decision), or confirmed dead
//! upstream (with the evidence).
//! Phase 8's completion condition otherwise uses property-based
//! verification (`PORTING-PLAN.md` §5), not a trajectory oracle, and CHOMP
//! specifically is not the one Phase-8 planner (`cspace_planners::pilz`) with
//! directly comparable deterministic output — one op is the exception:
//! `chomp_quad_cost_inverse` (round 18, requested round 17 in
//! `doc/oracle-request-quad-cost-inv.md`), backing
//! `tests/chomp_quad_cost_inverse_parity.rs`'s direct element-by-element
//! comparison of [`cost::ChompCost::quadratic_cost_inverse`] against real
//! Eigen output, closing the decomposition-family gap round 16 could only
//! residual-check — see [`cost`]'s module doc for the measured numbers. What
//! else is pinned by unit test: [`trajectory::ChompTrajectory`]'s
//! copy-with-padding indexing/`full_trajectory_index_` convention,
//! [`cost::ChompCost`]'s finite-difference boundary truncation,
//! [`optimizer`]'s weighted-combination and joint-limit-repair formulas,
//! each checked against a hand-rolled recomputation of the same upstream
//! formula, not merely "it runs" — and
//! `cspace_core::sampling`'s own [`MultivariateGaussian`] shape/positive-definite
//! rejection and empirical mean/variance/correlation convergence (that
//! crate's tests, not this one's — see above). [`planner::solve`] is pinned
//! by boundary-condition unit tests (bad start/goal state, wrong goal
//! count, non-joint goal, every `trajectory_initialization_method`
//! variant, the continuous-joint wraparound fix) rather than a trajectory
//! oracle, for the same reason the rest of this crate is: CHOMP has no
//! directly comparable deterministic output.

/// `ChompParameters` and its trajectory-initialization-method validation —
/// see the module doc's `chomp_parameters.{hpp,cpp}` entry.
pub mod parameters;

/// `DIFF_RULE_LENGTH`/`DIFF_RULES` finite-difference stencils and CHOMP's own
/// angle-normalization helpers — see the module doc's `chomp_utils.hpp`
/// entry.
pub mod utils;

/// `ChompTrajectory` — see the module doc's `chomp_trajectory.{hpp,cpp}`
/// entry.
pub mod trajectory;

/// `ChompCost` — see the module doc's `chomp_cost.{hpp,cpp}` entry.
pub mod cost;

/// The portable numeric core of `ChompOptimizer` — see the module doc's
/// `chomp_optimizer.{hpp,cpp}` entry.
pub mod optimizer;

/// `ChompPlanner::solve` — see the module doc's `chomp_planner.{hpp,cpp}`
/// entry.
pub mod planner;

pub use cost::ChompCost;
pub use cspace_core::sampling::MultivariateGaussian;
pub use optimizer::{ChompExit, ChompLoopTrace, ChompObjective, ChompObjectiveProgress};
pub use parameters::ChompParameters;
pub use planner::{
    ChompGoal, ChompRequest, ChompSolution, GoalJointConstraint, solve, solve_with_trace,
};
pub use trajectory::ChompTrajectory;
