// Copyright (c) 2026, moveit-rs contributors
// SPDX-License-Identifier: BSD-3-Clause

// GENERATED by tools/ci/verify-fcl-tangency-dispatch.sh --emit
//   crates/moveit-collision/src/fcl_tangency_table.rs
// Do not hand-edit: running tools/ci/verify-fcl-tangency-dispatch.sh with no
// arguments fails if this drifts from a fresh parse of the oracle image's own
// `gjk_solver_libccd-inl.h` -- see that script's module doc for what its
// third check verifies.

//! fcl's non-libccd (specialised) shape-intersect registrations, restricted
//! to the four kinds `crates/moveit-collision/src/parry.rs`'s `TangencyKind`
//! classifies a shape into (`Box`/`Sphere`/`Cylinder`/`Cone` -- `Mesh` is not
//! in this table; its own measured, per-paired-kind rule lives in
//! `crate::mesh_tangency_table` instead, since fcl maps it to a `BVHModel`
//! traversal this header does not register). Row/column order matches the
//! array below; the table is symmetric because
//! `FCL_GJK_LIBCCD_SHAPE_SHAPE_INTERSECT` registers both directions.

pub(crate) const SPECIALISED: [[bool; 4]; 4] = [
    //             box    sphere cylinder cone
    /* box      */ [true, true, false, false],
    /* sphere   */ [true, true, true, false],
    /* cylinder */ [false, true, false, false],
    /* cone     */ [false, false, false, false],
];
