// Copyright (c) 2026, moveit-rs contributors
// SPDX-License-Identifier: BSD-3-Clause

// GENERATED by tools/ci/verify-fcl-tangency-dispatch.sh --emit
//   crates/cspace-collision/src/fcl_tangency_table.rs
// Do not hand-edit: running tools/ci/verify-fcl-tangency-dispatch.sh with no
// arguments fails if this drifts from a fresh parse of the oracle image's own
// `gjk_solver_libccd-inl.h` -- see that script's module doc for what its
// third check verifies.

//! fcl's non-libccd (specialised) shape-intersect registrations, restricted
//! to the four kinds `crates/cspace-collision/src/parry.rs`'s `TangencyKind`
//! classifies a shape into (`Box`/`Sphere`/`Cylinder`/`Cone` -- `Mesh` is not
//! in this table; its own measured, per-paired-kind rule lives in
//! `crate::mesh_tangency_table` instead, since fcl maps it to a `BVHModel`
//! traversal this header does not register). Row/column order matches the
//! array below; the table is symmetric because
//! `FCL_GJK_LIBCCD_SHAPE_SHAPE_INTERSECT` registers both directions.
//!
//! Provenance, independent of the oracle image this file is machine
//! generated from (that mechanism is docker-gated --
//! `tools/ci/verify-fcl-tangency-dispatch.sh`'s own doc -- and its cited
//! `doc/upstream-bugs.md` entry no longer exists, deleted by `f7186386` when
//! the porting-doc tree was replaced by `GOALS.md`, so that particular trail
//! cannot be followed further): the same four registrations, re-derived by
//! hand against a live `/home/stevek/work/fcl` checkout at
//! `0.7.0-17-ge5efcc4`, `rg`-searched rather than parsed by script, but
//! against the identical macros `verify-fcl-tangency-dispatch.sh --emit`
//! reads. `gjk_solver_libccd-inl.h:245,246,250,252` --
//! `FCL_GJK_LIBCCD_SHAPE_INTERSECT(Sphere, detail::sphereSphereIntersect)`,
//! `FCL_GJK_LIBCCD_SHAPE_INTERSECT(Box, detail::boxBoxIntersect)`,
//! `FCL_GJK_LIBCCD_SHAPE_SHAPE_INTERSECT(Sphere, Box,
//! detail::sphereBoxIntersect)`,
//! `FCL_GJK_LIBCCD_SHAPE_SHAPE_INTERSECT(Sphere, Cylinder,
//! detail::sphereCylinderIntersect)` -- are exactly the four registrations
//! behind the table's six `true` cells below, no more and no fewer: the
//! two `SHAPE_INTERSECT` (self-pair) registrations set one cell each
//! (`box`x`box`, `sphere`x`sphere`), and the two `SHAPE_SHAPE_INTERSECT`
//! (cross-pair) registrations set two cells each, per this file's own
//! symmetric-registration note above (`sphere`x`box`/`box`x`sphere`,
//! `sphere`x`cylinder`/`cylinder`x`sphere`) -- 1 + 1 + 2 + 2 = 6. Every other
//! `FCL_GJK_LIBCCD_SHAPE(_SHAPE)?_INTERSECT` line in that header
//! (`:248,254-260,262-267`) names `Capsule`, `Halfspace`, `Plane`,
//! `Ellipsoid` or `Convex`, none of which is one of these four kinds; in
//! particular `Cone` never appears as either argument to either macro
//! against `Box`, `Sphere` or `Cylinder`, or against itself, in this header
//! at all. `gjk_solver_indep-inl.h` (fcl's alternate, non-libccd GJK
//! backend) registers the identical four pairs against the identical
//! algorithm functions (`:249,250,254,256`), so which solver `fcl::collide`
//! picks does not change this table; `GST_LIBCCD` is fcl's own default
//! regardless (`collision_request.h:102`).
//!
//! The `false` cells are not the same strength of claim as the `true` ones.
//! A `true` cell is a single closed-form routine, proven non-strict at the
//! boundary by reading its body, all four checked directly rather than
//! cited from elsewhere in this crate: `boxBoxIntersect`/`boxBox2`
//! (`box_box-inl.h:858`) rejects only on the 15 SAT axes'
//! `if(s2 > 0) { *return_code = 0; return 0; }`
//! (`:302,314,326,339,351,363,406,424,442,461,479,497,516,534,552`);
//! `sphereBoxIntersect` (`sphere_box-inl.h:98`) only on
//! `squared_distance > r * r` (`:119`); `sphereSphereIntersect`
//! (`sphere_sphere-inl.h:66`) only on `len > s1.radius + s2.radius`
//! (`:72`); `sphereCylinderIntersect` (`sphere_cylinder-inl.h:114`) only
//! on `p_SN_squared_dist > r_s * r_s` (`:136`). All four use a strict
//! `>`, so an exact-zero gap always falls through to a reported contact
//! in every `true` cell -- fcl cannot itself report no-contact for a
//! true touch in any of them. A `false` cell means
//! no such routine is registered for that pair at all: `cone` has zero
//! registrations against `box`, `sphere`, `cylinder` or itself in either
//! header, so every cell in its row and column falls through to fcl's
//! generic libccd MPR path, which the oracle image's probe measured `false`
//! at the one tie configuration it constructed. That is consistent with,
//! but weaker than, an algebraic guarantee: `discoverPortal`
//! (`/home/stevek/work/libccd`, checkout `7931e76`, `mpr.c:189,209,232`)
//! rejects on `ccdIsZero(dot) || dot < 0`, a test over the direction MPR's
//! portal discovery happens to pick, unlike the closed-form routines'
//! orientation-independent `s2 > 0`. A `false` cell reaching
//! `fcl_tangency_verdict` is `Some(false)`, not `None` --
//! `touches_at_tie`'s `.unwrap_or(true)` never applies to it, so a cone
//! pair sitting inside the rounding band reads as the positive "not
//! touching" this table asserts, not an unknown the fallback would
//! otherwise resolve to "touching". This crate has not measured whether
//! that holds at every cone-pair orientation, only the one the oracle probe
//! constructed.

pub(crate) const SPECIALISED: [[bool; 4]; 4] = [
    //             box    sphere cylinder cone
    /* box      */ [true, true, false, false],
    /* sphere   */ [true, true, true, false],
    /* cylinder */ [false, true, false, false],
    /* cone     */ [false, false, false, false],
];
