// How far `fcl::distance` moves, on the shape pair prbt's own self-check
// leans on, when the only thing changed is the GJK stopping threshold that
// MoveIt leaves at its default.
//
// `distanceCallback` builds its request as
// `fcl::DistanceRequestd(cdata->req->enable_nearest_points)`
// (`moveit_core/collision_detection_fcl/src/collision_common.cpp:603`), which
// fills the remaining parameters from the constructor defaults in
// `fcl/narrowphase/distance_request.h`: `rel_err = 0`, `abs_err = 0`,
// `distance_tolerance = 1e-6`, `gjk_solver_type = GST_LIBCCD`. That last pair
// is the whole subject here -- `distance_tolerance` is documented as "the
// threshold used in GJK algorithm to stop distance iteration", a *progress*
// threshold, not a bound on the answer's error.
//
// The pair is `fixtures/prbt.urdf`'s own: `prbt_link_4`'s SECOND collision box
// (`fixtures/prbt.urdf:319`, `0.09 x 0.06 x 0.12`) against `prbt_base_link`'s
// collision cylinder (`length 0.13`, `radius 0.09275`). `prbt_link_4` carries
// two boxes; this is not the other one (`fixtures/prbt.urdf:313`, `0.121 x
// 0.08 x 0.17`, PORTING-PLAN.md §284.4's "정정 (§284)" paragraph). PORTING-PLAN.md
// §284.4 measured that at the sweep's own worst separated-branch case (case
// 4697), it is the second box, not the first, whose distance to the cylinder
// lands next to both the oracle's and this port's published values -- the
// first box sits `7.3e-3`/`7.4e-3` away, 82x the residual under judgement.
// Neither ordering of box/cylinder has a non-libccd distance specialisation
// in fcl, so both go through GJK, which is what makes the threshold visible
// at all.
//
// Emits one CSV row per pose. The poses are generated by an xorshift64 seeded
// with a fixed constant, so the run replays exactly.
#include <fcl/fcl.h>

#include <cmath>
#include <cstdint>
#include <cstdio>
#include <memory>

using S = double;

namespace {

std::uint64_t rng_state = 88172645463325252ULL;

// xorshift64, taken here rather than <random> so the sequence does not depend
// on a standard-library implementation: a probe whose poses move between
// toolchains cannot pin a number.
double next_unit()
{
  rng_state ^= rng_state << 13;
  rng_state ^= rng_state >> 7;
  rng_state ^= rng_state << 17;
  return static_cast<double>(rng_state >> 11) / 9007199254740992.0;
}

// Shoemake's uniform random rotation.
Eigen::Quaternion<S> next_rotation()
{
  const double u1 = next_unit();
  const double u2 = next_unit();
  const double u3 = next_unit();
  const double a = std::sqrt(1.0 - u1);
  const double b = std::sqrt(u1);
  return Eigen::Quaternion<S>(a * std::sin(2.0 * M_PI * u2), a * std::cos(2.0 * M_PI * u2),
                              b * std::sin(2.0 * M_PI * u3), b * std::cos(2.0 * M_PI * u3));
}

double distance_with(const std::shared_ptr<fcl::CollisionGeometry<S>>& g1,
                     const fcl::Transform3<S>& t1,
                     const std::shared_ptr<fcl::CollisionGeometry<S>>& g2,
                     const fcl::Transform3<S>& t2, S tolerance, fcl::GJKSolverType solver)
{
  fcl::CollisionObject<S> o1(g1, t1);
  fcl::CollisionObject<S> o2(g2, t2);
  fcl::DistanceRequest<S> req(false, false, 0.0, 0.0, tolerance, solver);
  fcl::DistanceResult<S> res;
  return fcl::distance(&o1, &o2, req, res);
}

}  // namespace

int main()
{
  // prbt_link_4's SECOND <collision> box (fixtures/prbt.urdf:319) and
  // prbt_base_link's <collision> cylinder, verbatim from fixtures/prbt.urdf.
  // Was fixtures/prbt.urdf:313's box (0.121, 0.08, 0.17) -- see the module
  // comment above and PORTING-PLAN.md §284.4.
  auto box = std::make_shared<fcl::Box<S>>(0.09, 0.06, 0.12);
  auto cyl = std::make_shared<fcl::Cylinder<S>>(0.09275, 0.13);

  std::printf("idx,d_default,d_tight,d_indep\n");
  int emitted = 0;
  // Bounded: 20000 draws is the ceiling, not the target. The loop stops at
  // 2000 separated poses, and a run that cannot find them says so rather
  // than spinning.
  for (int draw = 0; draw < 20000 && emitted < 2000; ++draw)
  {
    fcl::Transform3<S> t1 = fcl::Transform3<S>::Identity();
    fcl::Transform3<S> t2 = fcl::Transform3<S>::Identity();
    t1.linear() = next_rotation().toRotationMatrix();
    t2.linear() = next_rotation().toRotationMatrix();
    // Offsets in the band the prbt sweep's own separated outliers sit in
    // (oracle values 6.1e-3 to 5.8e-2 apart), reached by drawing a direction
    // and a radius just above the two shapes' combined extent.
    const double dx = next_unit() * 2.0 - 1.0;
    const double dy = next_unit() * 2.0 - 1.0;
    const double dz = next_unit() * 2.0 - 1.0;
    const double norm = std::sqrt(dx * dx + dy * dy + dz * dz);
    if (norm < 1e-9)
    {
      continue;
    }
    const double radius = 0.16 + next_unit() * 0.09;
    t2.translation() = Eigen::Matrix<S, 3, 1>(dx / norm * radius, dy / norm * radius, dz / norm * radius);

    const double d_default = distance_with(box, t1, cyl, t2, 1e-6, fcl::GST_LIBCCD);
    // Only the separated branch is the subject: below zero `fcl::distance`
    // reports a sentinel and MoveIt replaces the value from a contact set
    // entirely, which is a different measurement (see
    // `doc/upstream-bugs.md`'s three distanceCallback entries).
    if (!(d_default > 0.0))
    {
      continue;
    }
    const double d_tight = distance_with(box, t1, cyl, t2, 1e-12, fcl::GST_LIBCCD);
    const double d_indep = distance_with(box, t1, cyl, t2, 1e-12, fcl::GST_INDEP);
    std::printf("%d,%.17e,%.17e,%.17e\n", emitted, d_default, d_tight, d_indep);
    ++emitted;
  }
  if (emitted < 2000)
  {
    std::fprintf(stderr, "only %d separated poses in 20000 draws\n", emitted);
    return 2;
  }
  return 0;
}
