#!/usr/bin/env python3
"""Measure the port-coverage split of the upstream corpus.

Two independent things are measured and printed:

  1. The CORPUS -- upstream files this port is on the hook for, enumerated
     from the reference checkout by the rules in `corpus_files()` below.
  2. The CITED set -- upstream paths named inside a
     `// Ported from moveit2 @ <sha>:` header block of some `.rs` file
     under `crates/` or `ros/`.

A corpus file is PORTED when its path is in the cited set, UNPORTED
otherwise.  Nothing here classifies an unported file as gap vs decided
non-port; that lives in `doc/port-coverage.md`, which this script's
`--check` mode reconciles against.

Usage:
    tools/ci/measure-port-coverage.py [--upstream DIR] [--list-unported]
                                      [--list-ported] [--check DOC]
"""

from __future__ import annotations

import argparse
import os
import re
import sys

DEFAULT_UPSTREAM = "/home/stevek/work/moveit2"

# moveit_core subdirectories the plan removes from the port target.
#   controller_manager           -- PORTING-PLAN.md 1: "[범위 밖]"
#   collision_detection_bullet   -- PORTING-PLAN.md 1: "[드롭]"
#   collision_detection_fcl      -- PORTING-PLAN.md 1: "[parry로 대체]"
#   version                      -- build-stamp only; see doc/port-coverage.md 1
CORE_EXCLUDED_SUBDIRS = {
    "controller_manager",
    "collision_detection_bullet",
    "collision_detection_fcl",
    "version",
}

# Package trees the corpus is drawn from.  moveit_planners is taken by the
# three planners PORTING-PLAN.md 5 Phase 8 names; ompl is replaced by a
# native planner (D3), test_configs / _testutils are test resources.
CORPUS_ROOTS = [
    "moveit_core",
    "moveit_kinematics",
    "moveit_planners/chomp",
    "moveit_planners/stomp",
    "moveit_planners/pilz_industrial_motion_planner",
]

SOURCE_EXTS = (".cpp", ".hpp", ".h")

# Autogenerated `.h` forwarders (moveit2 PR #3113).  Identified by content,
# not by name, so a real `.h` header is never dropped by accident.
SHIM_MARKER = ".h header is obsolete. Please use the .hpp header instead."

CITE_HEADER = re.compile(r"^\s*//\s*Ported from moveit2 @ [0-9a-f]{40}:\s*$")

# The citation-block grammar, as it is actually written in this tree (every
# form below occurs; `--dump-grammar` prints one example of each):
#
#   //   <pkg>/<dir>/<file>.hpp                      plain path
#   //   <pkg>/<dir>/<file>.hpp (class Path)         path + annotation
#   //   <pkg>/<dir>/{a/b.hpp,c/d.cpp}               brace expansion
#   //   <pkg>/<dir>/                                whole directory
#   //     <file>.hpp                                  ... its members
#   //   (SomeSymbol::method, cpp:12-34)             continuation prose
#
# A block runs from the marker to the first empty `//` line, non-comment
# line, or `not ported` label -- so a "Considered and deliberately not
# ported:" list below the block is never read as a citation.
# `--check`'s row grammar: `| `<path>` | <class> | <evidence> | <note> |`.
# The reconciliation below reads the first cell only, so a row can be
# malformed to the right of it and still reconcile -- which is how six rows
# lost their closing `|` and three grew a fifth column at an unescaped `|`
# inside a `rg ... | wc -l` code span, where GFM truncates the rendered cell.
DOC_ROW_CELLS = 4
DOC_ROW_START = re.compile(r"^\| `moveit_[^`]+` \|")
DOC_CELL_SPLIT = re.compile(r"(?<!\\)\|")

COMMENT = re.compile(r"^\s*//(.*)$")
DIR_LINE = re.compile(r"^(moveit_[A-Za-z0-9_./-]*/)$")
PATH_LINE = re.compile(r"^(moveit_[A-Za-z0-9_./-]+\.(?:cpp|hpp|h|cc))(\s.*)?$")
BRACE_LINE = re.compile(r"^(moveit_[A-Za-z0-9_./-]*/)\{([^}]*)\}\s*$")
MEMBER_LINE = re.compile(r"^([A-Za-z0-9_.-]+\.(?:cpp|hpp|h|cc))(\s.*)?$")


def corpus_files(upstream: str) -> list[str]:
    """Enumerate the corpus, relative to `upstream`."""
    out = []
    for root in CORPUS_ROOTS:
        for dirpath, dirnames, filenames in os.walk(os.path.join(upstream, root)):
            rel_dir = os.path.relpath(dirpath, upstream)
            parts = rel_dir.split(os.sep)
            # no `test`/`tests` path component anywhere
            if "test" in parts or "tests" in parts:
                dirnames[:] = []
                continue
            if parts[0] == "moveit_core" and len(parts) > 1:
                if parts[1] in CORE_EXCLUDED_SUBDIRS:
                    dirnames[:] = []
                    continue
            for fn in filenames:
                if not fn.endswith(SOURCE_EXTS):
                    continue
                abs_path = os.path.join(dirpath, fn)
                if fn.endswith(".h") and is_shim(abs_path):
                    continue
                out.append(os.path.relpath(abs_path, upstream))
    return sorted(out)


def is_shim(path: str) -> bool:
    with open(path, encoding="utf-8", errors="replace") as fh:
        return SHIM_MARKER in fh.read()


def rs_files(repo: str) -> list[str]:
    out = []
    for top in ("crates", "ros"):
        for dirpath, _dirnames, filenames in os.walk(os.path.join(repo, top)):
            if "target" in dirpath.split(os.sep):
                continue
            for fn in filenames:
                if fn.endswith(".rs"):
                    out.append(os.path.join(dirpath, fn))
    return sorted(out)


def cited_paths(repo: str, corpus: list[str]) -> dict[str, list[str]]:
    """Map upstream path -> the .rs files citing it in a header block.

    A whole-directory citation resolves to every corpus file under it, so
    `corpus` is an input here rather than something derived afterwards.
    """
    cites: dict[str, list[str]] = {}

    def add(path: str, rs: str) -> None:
        cites.setdefault(path, []).append(os.path.relpath(rs, repo))

    for rs in rs_files(repo):
        with open(rs, encoding="utf-8", errors="replace") as fh:
            lines = fh.readlines()
        i = 0
        while i < len(lines):
            if not CITE_HEADER.match(lines[i]):
                i += 1
                continue
            i += 1
            prefix = None
            prefix_members = 0

            def close_prefix() -> None:
                # A directory line with no indented members under it is a
                # citation of the whole directory (`moveit_core/planning_scene/`
                # in moveit-scene); one *with* members only scopes them.
                nonlocal prefix, prefix_members
                if prefix and prefix_members == 0:
                    for f in corpus:
                        if f.startswith(prefix):
                            add(f, rs)
                prefix, prefix_members = None, 0

            while i < len(lines):
                m = COMMENT.match(lines[i])
                if not m:
                    break
                body = m.group(1)
                if not body.strip() or "not ported" in body:
                    break
                i += 1
                text = body.strip()
                indent = len(body) - len(body.lstrip())
                mm = MEMBER_LINE.match(text)
                if mm and prefix and indent > 3:
                    add(prefix + mm.group(1), rs)
                    prefix_members += 1
                    continue
                mb = BRACE_LINE.match(text)
                if mb:
                    close_prefix()
                    for part in mb.group(2).split(","):
                        add(mb.group(1) + part.strip(), rs)
                    continue
                md = DIR_LINE.match(text)
                if md:
                    close_prefix()
                    prefix = md.group(1)
                    continue
                mp = PATH_LINE.match(text)
                if mp:
                    close_prefix()
                    add(mp.group(1), rs)
                    continue
                # anything else is continuation prose: ignored, not fatal
            close_prefix()
    return cites


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", default=DEFAULT_UPSTREAM)
    ap.add_argument("--repo", default=os.getcwd())
    ap.add_argument("--list-unported", action="store_true")
    ap.add_argument("--list-ported", action="store_true")
    ap.add_argument("--list-cited-outside-corpus", action="store_true")
    ap.add_argument(
        "--check",
        metavar="DOC",
        help="reconcile the unported list against a coverage doc's table",
    )
    args = ap.parse_args()

    corpus = corpus_files(args.upstream)
    cites = cited_paths(args.repo, corpus)
    corpus_set = set(corpus)

    ported = [f for f in corpus if f in cites]
    unported = [f for f in corpus if f not in cites]
    outside = sorted(p for p in cites if p not in corpus_set)

    print(f"corpus   {len(corpus)}")
    print(f"ported   {len(ported)}")
    print(f"unported {len(unported)}")
    print(f"cited-outside-corpus {len(outside)}")

    if args.list_ported:
        print("\n--- ported ---")
        for f in ported:
            print(f)
    if args.list_unported:
        print("\n--- unported ---")
        for f in unported:
            print(f)
    if args.list_cited_outside_corpus:
        print("\n--- cited, outside corpus ---")
        for f in outside:
            print(f)

    if args.check:
        with open(args.check, encoding="utf-8") as fh:
            doc = fh.read()
        # A list, not a set: comparing sets makes a duplicated row invisible
        # -- both differences below stay empty and `len(rows)` reports the
        # deduplicated count, so a 96-row file printed "95 rows == 95
        # unported" and exited 0.  The row count in the closing line is the
        # file's own, which is what makes that line an assertion about the
        # document rather than a restatement of the set it was derived from.
        listed = re.findall(r"^\| `(moveit_[^`]+)` \|", doc, re.M)
        malformed = []
        for lineno, line in enumerate(doc.splitlines(), 1):
            if not DOC_ROW_START.match(line):
                continue
            if not line.endswith("|"):
                malformed.append((lineno, "no closing `|`"))
                continue
            cells = DOC_CELL_SPLIT.split(line)[1:-1]
            if len(cells) != DOC_ROW_CELLS:
                malformed.append(
                    (lineno, f"{len(cells)} cells, want {DOC_ROW_CELLS} -- unescaped `|`?")
                )
        rows = set(listed)
        duplicated = sorted({f for f in rows if listed.count(f) > 1})
        missing = sorted(set(unported) - rows)
        extra = sorted(rows - set(unported))
        for f in missing:
            print(f"MISSING ROW  {f}", file=sys.stderr)
        for f in extra:
            print(f"STALE ROW    {f}", file=sys.stderr)
        for f in duplicated:
            print(f"DUPLICATE ROW  {f} ({listed.count(f)} rows)", file=sys.stderr)
        for lineno, why in malformed:
            print(f"MALFORMED ROW  {args.check}:{lineno}: {why}", file=sys.stderr)
        if missing or extra or duplicated or malformed:
            print(
                f"FAIL {args.check}: {len(missing)} missing, {len(extra)} stale, "
                f"{len(duplicated)} duplicated, {len(malformed)} malformed",
                file=sys.stderr,
            )
            return 1
        print(
            f"OK {args.check}: {len(listed)} rows == {len(unported)} unported, "
            f"all {DOC_ROW_CELLS}-cell"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
