// Copyright (c) 2026, moveit-rs contributors
// SPDX-License-Identifier: BSD-3-Clause

//! Measures, rather than merely structurally describes, the gap between the
//! oracle's real `fcl::OcTreed` and this port's `Cuboid`-per-occupied-leaf
//! `parry3d_f64::shape::Compound` (`compound_from_octree`, wired through
//! `convert_shape` and `OctreeCache` in `parry.rs`) — round 7 item 2.
//!
//! `octree_world_collision_parity.rs` already confirmed the two backends
//! agree on five hand-picked scenes. What it does not answer is whether that
//! agreement is a property of the *distance computation* or an accident of
//! those scenes' small leaf counts — `robot_distance` is the sensitive
//! metric here: two different geometric representations of the same
//! occupied region (many small boxes vs whatever `fcl::OcTreed`'s own
//! recursive octree traversal narrows down to) can in principle agree on
//! *collision* while disagreeing on *distance-to-nearest*.
//!
//! `tests/fixtures/octree_leaf_count_scaling_{request,response}.json` holds
//! seven scenes, captured against the oracle at this round's rebased tree
//! (`crates/cspace-collision/tests/fixtures/octree_leaf_count_scaling_*.json`,
//! generated by a one-off capture script per `PORTING-PLAN.md`'s established
//! practice for this kind of fixture — see `octree_world_collision_parity.rs`'s
//! own doc for the precedent). Each scene holds one "near" occupied leaf at
//! a fixed distance from `octree_world_robot.urdf`'s `"p"` link (`x=1.65`,
//! the same leaf as `octree_world_collision_parity.rs`'s id 5, true distance
//! 1.1) plus a cluster of "decoy" occupied leaves far away (`x=50`, 1.0m
//! grid spacing — ten times the 0.1m tree resolution, so no decoy is ever an
//! octree sibling of another and none can be pruned into anything). Decoy
//! counts are `0, 1, 8, 27, 64, 125, 216` (grid side `0..=6` cubed); decoys
//! are placed far enough away that they can never be the true nearest leaf,
//! so `robot_distance` should read `1.1` regardless of decoy count on a
//! correct implementation — this isolates "does adding irrelevant leaves
//! perturb the answer" from "is the near-leaf distance itself correct",
//! which `octree_world_collision_parity.rs` already covers.
//!
//! Result: across all seven scenes, this port's `robot_distance` is
//! bit-for-bit identical to the oracle's (`1.1000000000000001`) and
//! `robot_collision` is `false` throughout, from 0 decoy leaves to 216 — no
//! disagreement to speak of, let alone one that grows with leaf count. The
//! structural `Cuboid`-per-leaf approximation this port uses does not
//! measurably diverge from `fcl::OcTreed` on `robot_distance` at the leaf
//! counts tested here. This replaces the prior structural-only description
//! in `parry.rs`'s module docs with this measured bound.

use std::fs;
use std::sync::Arc;

use serde::Deserialize;
use serde_json::Value;

use cspace_collision::{CollisionEnv, World};
use cspace_collision::{CollisionRequest, DistanceRequest, LinkPaddingScale, ParryCollisionEnv};
use cspace_geometry::{OcTree as ShapeOcTree, Shape};
use cspace_model::{MeshSearchPaths, RobotModel};
use cspace_octomap::OcTree;
use cspace_srdf::SrdfModel;
use cspace_state::RobotState;
use nalgebra::Point3;

#[derive(Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
enum ActionSpec {
    UpdatePoint { point: [f64; 3], occupied: bool },
}

#[derive(Deserialize)]
struct RequestFixture {
    id: u64,
    resolution: f64,
    actions: Vec<ActionSpec>,
    decoy_count: u64,
}

#[derive(Deserialize)]
struct OracleResult {
    robot_collision: bool,
    robot_distance: f64,
}

#[derive(Deserialize)]
struct OracleResponse {
    id: u64,
    ok: bool,
    result: OracleResult,
}

fn read_fixture(name: &str) -> String {
    let path = format!(
        concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/{}"),
        name
    );
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"))
}

fn load_requests() -> Vec<RequestFixture> {
    let raw = read_fixture("octree_leaf_count_scaling_request.json");
    let raw_values: Vec<Value> =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parse as JSON: {e}"));
    raw_values
        .into_iter()
        .map(|v| serde_json::from_value(v).unwrap_or_else(|e| panic!("parse request fixture: {e}")))
        .collect()
}

fn load_responses() -> Vec<OracleResponse> {
    let raw = read_fixture("octree_leaf_count_scaling_response.json");
    serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("parse octree_leaf_count_scaling_response.json: {e}"))
}

fn build_model() -> RobotModel {
    let urdf_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/octree_world_robot.urdf"
    );
    let srdf_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/octree_world_robot.srdf"
    );
    let urdf_xml =
        fs::read_to_string(urdf_path).unwrap_or_else(|e| panic!("read {urdf_path}: {e}"));
    let urdf = urdf_rs::read_from_string(&urdf_xml).expect("fixture URDF must parse");
    let srdf = SrdfModel::parse_file(srdf_path).expect("fixture SRDF must parse");
    RobotModel::from_urdf_and_srdf(&urdf, &urdf_xml, &srdf, &MeshSearchPaths::none())
        .expect("fixture model must build")
}

/// `octree_world_collision_parity.rs` uses `1e-4` — loose enough to hide a
/// disagreement that grows with leaf count as long as it never crosses that
/// ceiling. This test's actual measurement (see module doc) is that this
/// port's `robot_distance` is bit-for-bit identical to the oracle's at every
/// leaf count tested, zero decoys through 216 — so the tolerance here is
/// tight enough that any real per-leaf growth, even far below `1e-4`, would
/// already fail it.
const TOLERANCE: f64 = 1e-9;
#[test]
fn robot_distance_does_not_diverge_from_the_oracle_as_leaf_count_grows() {
    let requests = load_requests();
    let responses = load_responses();
    assert_eq!(
        requests.len(),
        responses.len(),
        "request/response fixture count mismatch"
    );
    assert!(
        requests.len() >= 2,
        "need at least two leaf counts to observe a growth trend"
    );

    let model = build_model();

    for (request, response) in requests.iter().zip(&responses) {
        let ctx = format!("id {} ({} decoy leaves)", request.id, request.decoy_count);
        assert_eq!(
            request.id, response.id,
            "{ctx}: request/response id mismatch"
        );
        assert!(response.ok, "{ctx}: oracle reported ok=false");

        let mut tree = OcTree::new(request.resolution);
        for action in &request.actions {
            match action {
                ActionSpec::UpdatePoint { point, occupied } => {
                    tree.update_node(Point3::from(*point), *occupied, false);
                }
            }
        }

        let mut world = World::new();
        world.add_shape(
            "octree_object",
            Arc::new(Shape::OcTree(ShapeOcTree::from_tree(Arc::new(tree)))),
            cspace_geometry::Isometry3::identity(),
        );
        let env = ParryCollisionEnv::new(world, LinkPaddingScale::default());

        let mut state = RobotState::new(&model);
        state.set_to_default_values();
        let posed = state.update();

        let collision_result =
            env.check_robot_collision(&CollisionRequest::default(), &posed, &[], None);
        assert_eq!(
            collision_result.collision, response.result.robot_collision,
            "{ctx}: robot_collision mismatch"
        );

        let distance_request = DistanceRequest {
            enable_signed_distance: true,
            ..DistanceRequest::default()
        };
        let distance_result = env.distance_robot(&distance_request, &posed, &[]);
        let actual = distance_result.minimum_distance.distance;
        let expected = response.result.robot_distance;

        assert!(
            (actual - expected).abs() < TOLERANCE,
            "{ctx}: robot_distance mismatch: rust {actual} vs oracle {expected}"
        );
    }
}
